name: CI
on: push
jobs:
  style:
    uses: PlaceOS/.github/.github/workflows/crystal-style.yml@main

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        crystal:
          - 1.1.1
          - 1.4.0
          - nightly
    steps:
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - uses: actions/checkout@v2
      - run: shards install --ignore-crystal-version
      - name: Run tests
        run: crystal spec --error-trace -v
